- id: poetry-to-requirements
  name: Poetry to pip requirements
  description: Convert Poetry dependencies to pip requirements file
  entry: python poetry_to_requirements.py
  language: system
  always_run: true
