- id: poetry-to-requirements
  name: Poetry to pip requirements
  description: Convert Poetry dependencies to pip requirements file
  entry: poetry-to-requirements
  language: python
  always_run: true
